---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apisix-apache-org-v2-apisixconsumer
  failurePolicy: Ignore
  name: vapisixconsumer-v2.kb.io
  rules:
  - apiGroups:
    - apisix.apache.org
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apisixconsumers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apisix-apache-org-v2-apisixroute
  failurePolicy: Ignore
  name: vapisixroute-v2.kb.io
  rules:
  - apiGroups:
    - apisix.apache.org
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apisixroutes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apisix-apache-org-v2-apisixtls
  failurePolicy: Ignore
  name: vapisixtls-v2.kb.io
  rules:
  - apiGroups:
    - apisix.apache.org
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - apisixtlses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apisix-apache-org-v1alpha1-consumer
  failurePolicy: Ignore
  name: vconsumer-v1alpha1.kb.io
  rules:
  - apiGroups:
    - apisix.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - consumers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-networking-k8s-io-v1-gateway
  failurePolicy: Ignore
  name: vgateway-v1.kb.io
  rules:
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apisix-apache-org-v1alpha1-gatewayproxy
  failurePolicy: Ignore
  name: vgatewayproxy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - apisix.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gatewayproxies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-networking-k8s-io-v1-grpcroute
  failurePolicy: Ignore
  name: vgrpcroute-v1.kb.io
  rules:
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - grpcroutes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-networking-k8s-io-v1-httproute
  failurePolicy: Ignore
  name: vhttproute-v1.kb.io
  rules:
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httproutes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-k8s-io-v1-ingress
  failurePolicy: Ignore
  name: vingress-v1.kb.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-k8s-io-v1-ingressclass
  failurePolicy: Ignore
  name: vingressclass-v1.kb.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingressclasses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-networking-k8s-io-v1alpha2-tcproute
  failurePolicy: Ignore
  name: vtcproute-v1alpha2.kb.io
  rules:
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - tcproutes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-networking-k8s-io-v1alpha2-udproute
  failurePolicy: Ignore
  name: vudproute-v1alpha2.kb.io
  rules:
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - udproutes
  sideEffects: None
