apiVersion: apisix.apache.org.github.com/v2
kind: ApisixGlobalRule
metadata:
  labels:
    app.kubernetes.io/name: apisix-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: apisixglobalrule-sample
spec:
  # TODO(user): Add fields here
