name: APISIX Conformance Test

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go Env
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install kind
        run: |
          go install sigs.k8s.io/kind@v0.23.0

  conformance-test:
    timeout-minutes: 60
    needs: 
      - prepare
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go Env
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build images
        env:
          TAG: dev
          ARCH: amd64
          ENABLE_PROXY: "false"
          BASE_IMAGE_TAG: "debug"
          ADC_VERSION: "dev"
        run: |
          echo "building images..."
          make build-image

      - name: Launch Kind Cluster
        run: |
          make kind-up

      - name: Install And Run Cloud Provider KIND
        run: |
          go install sigs.k8s.io/cloud-provider-kind@latest
          nohup cloud-provider-kind > /tmp/kind-loadbalancer.log 2>&1 &
  
      - name: Install Gateway API And CRDs
        run: |
          make install

      - name: Loading Docker Image to Kind Cluster
        run: |
          make kind-load-ingress-image

      - name: Run Conformance Test
        shell: bash
        continue-on-error: true
        run: |
          make conformance-test-standalone
      
      - name: Get Logs from apisix-ingress-controller
        shell: bash
        run: |
          export KUBECONFIG=/tmp/apisix-ingress-cluster.kubeconfig
          kubectl logs -n apisix-conformance-test -l app=apisix-ingress-controller

      - name: Upload Gateway API Conformance Report
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: apisix-ingress-controller-conformance-report.yaml
          path: apisix-ingress-controller-conformance-report.yaml

      - name: Format Conformance Test Report
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo '# conformance test report' > report.md
          echo '```yaml' >> report.md
          cat apisix-ingress-controller-conformance-report.yaml >> report.md
          echo '```' >> report.md

      - name: Report Conformance Test Result to PR Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: 'apisix-conformance-test-report'
          message-path: |
            report.md
