name: lint

on:
  push:
    branches:
      - master
      - release-v2-dev
  pull_request:
    branches:
      - master
      - release-v2-dev

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go Env
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: check go path for debug
        run: go env

      - name: üõ©Ô∏è golangci-lint
        run: make lint

      - name: ¬©Ô∏è check-copyright
        run: make check-copyright

  crd-docs-check:
    name: Check CRD Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download crd-ref-docs
        run: |
          mkdir -p ./bin
          curl -L -o ./bin/crd-ref-docs.tar.gz https://github.com/elastic/crd-ref-docs/releases/download/v0.1.0/crd-ref-docs_0.1.0_Linux_x86_64.tar.gz
          tar -xzvf ./bin/crd-ref-docs.tar.gz -C ./bin
          chmod +x ./bin/crd-ref-docs
      - name: Generate CRD Docs
        run: |
          make generate-crd-docs
      - name: Check CRD Docs Diff
        run: |
          if ! git diff --exit-code -- docs/crd/api.md; then
            echo "docs/crd/api.md has changed. Please run 'make generate-crd-docs' and commit the updated file."
            exit 1
          fi
